# DataSource
spring.datasource.url=jdbc:postgresql://89.117.52.33:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
# Liquibase
spring.liquibase.change-log=classpath:db.changelog/public/db.changelog-master.yaml
spring.liquibase.drop-first=false
# Quartz Scheduler
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.jobStore.tablePrefix=public.qrtz_
# Redis
spring.data.redis.url=redis://89.117.52.33:6379/0
spring.data.redis.timeout=2000
# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-handlers-package=dev.ngb.base_stack.infrastructure.persistence.mybatis.type_handler
# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath*:graphql/**/
# Scalar
scalar.enabled=true
spring.threads.virtual.enabled=true
# Kafka
spring.kafka.bootstrap-servers=89.117.52.33:9095
spring.kafka.consumer.group-id=base_stack
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
# Logging
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.jdbc.support.JdbcTransactionManager=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
# OpenTelemetry
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://89.117.52.33:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://89.117.52.33:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://89.117.52.33:4318/v1/logs